[2024-09-05T11:33:38.338+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-05T11:33:38.619+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kezekte_etl.create_table scheduled__2024-09-04T00:00:00+00:00 [queued]>
[2024-09-05T11:33:38.636+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kezekte_etl.create_table scheduled__2024-09-04T00:00:00+00:00 [queued]>
[2024-09-05T11:33:38.637+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-05T11:33:38.675+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): create_table> on 2024-09-04 00:00:00+00:00
[2024-09-05T11:33:38.710+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=107) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T11:33:38.716+0000] {standard_task_runner.py:63} INFO - Started process 109 to run task
[2024-09-05T11:33:38.718+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kezekte_etl', 'create_table', 'scheduled__2024-09-04T00:00:00+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/kezekte_etl.py', '--cfg-path', '/tmp/tmpz71nwho1']
[2024-09-05T11:33:38.723+0000] {standard_task_runner.py:91} INFO - Job 203: Subtask create_table
[2024-09-05T11:33:38.791+0000] {task_command.py:426} INFO - Running <TaskInstance: kezekte_etl.create_table scheduled__2024-09-04T00:00:00+00:00 [running]> on host a0fd996fc1e4
[2024-09-05T11:33:38.966+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kezekte_etl' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-04T00:00:00+00:00'
[2024-09-05T11:33:38.974+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-05T11:33:39.014+0000] {sql.py:276} INFO - Executing: 
            create table if not exists transformed_animals (
                id serial PRIMARY KEY,
                chip_id varchar(255),
                type varchar(255),
                nickname varchar(255),
                gender varchar(255),
                breed varchar(255),
                passport_number varchar(255),
                register_date timestamp,
                birthday date,
                status varchar(255),
                ownership varchar(255),
                register_type varchar(255),
                tagging_location varchar(255),
                tagging_place varchar(255),
                tagging_date date,
                district_area varchar(255),
                date_vaccination varchar(255),
                date_sterilization_castration date,
                CONSTRAINT unique_passport unique (passport_number)
            )
        
[2024-09-05T11:33:39.044+0000] {base.py:84} INFO - Using connection ID 'postgresql_conn' for task execution.
[2024-09-05T11:33:39.055+0000] {base.py:84} INFO - Using connection ID 'postgresql_conn' for task execution.
[2024-09-05T11:33:39.058+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-05T11:33:39.060+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 431, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 551, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "172.19.0.3", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-09-05T11:33:39.087+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=kezekte_etl, task_id=create_table, run_id=scheduled__2024-09-04T00:00:00+00:00, execution_date=20240904T000000, start_date=20240905T113338, end_date=20240905T113339
[2024-09-05T11:33:39.109+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 203 for task create_table (connection to server at "172.19.0.3", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 109)
[2024-09-05T11:33:39.192+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-05T11:33:39.300+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-05T11:33:39.304+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
