[2024-09-06T11:47:05.258+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-06T11:47:05.267+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kezekte_etl.create_table manual__2024-09-06T11:46:52.187647+00:00 [queued]>
[2024-09-06T11:47:05.271+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kezekte_etl.create_table manual__2024-09-06T11:46:52.187647+00:00 [queued]>
[2024-09-06T11:47:05.271+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-06T11:47:05.276+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): create_table> on 2024-09-06 11:46:52.187647+00:00
[2024-09-06T11:47:05.286+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=151) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-06T11:47:05.288+0000] {standard_task_runner.py:63} INFO - Started process 152 to run task
[2024-09-06T11:47:05.288+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kezekte_etl', 'create_table', 'manual__2024-09-06T11:46:52.187647+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/kezekte_etl.py', '--cfg-path', '/tmp/tmp79y13fpn']
[2024-09-06T11:47:05.289+0000] {standard_task_runner.py:91} INFO - Job 357: Subtask create_table
[2024-09-06T11:47:05.308+0000] {task_command.py:426} INFO - Running <TaskInstance: kezekte_etl.create_table manual__2024-09-06T11:46:52.187647+00:00 [running]> on host 0aad73b8d37a
[2024-09-06T11:47:05.340+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kezekte_etl' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-06T11:46:52.187647+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-06T11:46:52.187647+00:00'
[2024-09-06T11:47:05.341+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-06T11:47:05.347+0000] {sql.py:276} INFO - Executing: 
            create table if not exists transformed_animals (
                id serial PRIMARY KEY,
                chip_id varchar(255),
                type varchar(255),
                nickname varchar(255),
                gender varchar(255),
                breed varchar(255),
                passport_number varchar(255),
                register_date timestamp,
                birthday date,
                status varchar(255),
                ownership varchar(255),
                register_type varchar(255),
                tagging_location varchar(255),
                tagging_place varchar(255),
                tagging_date date,
                district_area varchar(255),
                date_vaccination varchar(255),
                date_sterilization_castration date,
                CONSTRAINT unique_passport unique (passport_number)
            )
        
[2024-09-06T11:47:05.350+0000] {base.py:84} INFO - Using connection ID 'postgresql_conn' for task execution.
[2024-09-06T11:47:05.353+0000] {base.py:84} INFO - Using connection ID 'postgresql_conn' for task execution.
[2024-09-06T11:48:00.925+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-09-06T11:48:00.932+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-06T11:48:00.935+0000] {process_utils.py:132} INFO - Sending 15 to group 152. PIDs of all processes in the group: [152]
[2024-09-06T11:48:00.935+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 152
[2024-09-06T11:48:20.368+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-06T11:48:20.433+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=152, status='terminated', exitcode=0, started='11:47:04') (152) terminated with exit code 0
