[2024-07-30T17:10:29.112+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-30T17:10:29.125+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kezekte_etl.transform_data manual__2024-07-30T17:10:22.201220+00:00 [queued]>
[2024-07-30T17:10:29.128+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kezekte_etl.transform_data manual__2024-07-30T17:10:22.201220+00:00 [queued]>
[2024-07-30T17:10:29.129+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-30T17:10:29.134+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-07-30 17:10:22.201220+00:00
[2024-07-30T17:10:29.140+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1439) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-30T17:10:29.141+0000] {standard_task_runner.py:63} INFO - Started process 1441 to run task
[2024-07-30T17:10:29.141+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kezekte_etl', 'transform_data', 'manual__2024-07-30T17:10:22.201220+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/kezekte_etl.py', '--cfg-path', '/tmp/tmp5tcwogdh']
[2024-07-30T17:10:29.143+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask transform_data
[2024-07-30T17:10:29.171+0000] {task_command.py:426} INFO - Running <TaskInstance: kezekte_etl.transform_data manual__2024-07-30T17:10:22.201220+00:00 [running]> on host d6d2ff1599d5
[2024-07-30T17:10:29.216+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kezekte_etl' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-30T17:10:22.201220+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-30T17:10:22.201220+00:00'
[2024-07-30T17:10:29.217+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-30T17:10:29.231+0000] {base.py:84} INFO - Using connection ID 'postgresql_conn' for task execution.
[2024-07-30T17:10:29.233+0000] {sql.py:487} INFO - Running statement: 
        insert into raw_animals (chip_id, type, nickname, gender, breed, passport_number, register_date, birthday, status, ownership, 
                                register_type, tagging_location, tagging_place, tagging_date, district_area, date_vaccination, date_sterilization_castration)
        values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    , parameters: ('398010000240645', 'Собака', '-', 'Самец', 'Беспородная', 'KZD290724-0189473', '30.07.2024 15:36:34', '15.08.2021', 'На передаче', 'Бродячее', 'Мечение животного', 'Частный фонд "СтопОтлов"', 'Приют для животных', '29.07.2024', 'Сарыарка р.а.', '30.07.2024', 'Не стерилизован/кастрирован')
[2024-07-30T17:10:29.234+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-30T17:10:29.235+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kezekte_etl.py", line 78, in transform_data
    postgres_hook.run(insert_sql, parameters=(animal_id, animal_type, animal_nickname, animal_gender, animal_breed, animal_passport, animal_register, animal_birthday, anima_status, animal_ownership, animal_register_type, animal_tagging_location, animal_tagging_place, animal_tagging_date, animal_district_area, animal_date_vaccination, animal_date_sterilization_castration))
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 490, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.NumericValueOutOfRange: value "398010000240645" is out of range for type integer
LINE 4:         values ('398010000240645', 'Собака', '-', 'Самец', '...
                        ^

[2024-07-30T17:10:29.239+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=kezekte_etl, task_id=transform_data, run_id=manual__2024-07-30T17:10:22.201220+00:00, execution_date=20240730T171022, start_date=20240730T171029, end_date=20240730T171029
[2024-07-30T17:10:29.243+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 68 for task transform_data (value "398010000240645" is out of range for type integer
LINE 4:         values ('398010000240645', 'Собака', '-', 'Самец', '...
                        ^
; 1441)
[2024-07-30T17:10:29.283+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-30T17:10:29.293+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-30T17:10:29.293+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
