[2024-08-01T10:35:51.492+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-01T10:35:51.500+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kezekte_etl.transform_data manual__2024-08-01T10:26:01.842538+00:00 [queued]>
[2024-08-01T10:35:51.503+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kezekte_etl.transform_data manual__2024-08-01T10:26:01.842538+00:00 [queued]>
[2024-08-01T10:35:51.504+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-01T10:35:51.509+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-08-01 10:26:01.842538+00:00
[2024-08-01T10:35:51.528+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=337) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-01T10:35:51.530+0000] {standard_task_runner.py:63} INFO - Started process 339 to run task
[2024-08-01T10:35:51.530+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kezekte_etl', 'transform_data', 'manual__2024-08-01T10:26:01.842538+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/kezekte_etl.py', '--cfg-path', '/tmp/tmp_6z2bvfq']
[2024-08-01T10:35:51.532+0000] {standard_task_runner.py:91} INFO - Job 95: Subtask transform_data
[2024-08-01T10:35:51.556+0000] {task_command.py:426} INFO - Running <TaskInstance: kezekte_etl.transform_data manual__2024-08-01T10:26:01.842538+00:00 [running]> on host cd4398d9193e
[2024-08-01T10:35:51.592+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kezekte_etl' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T10:26:01.842538+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-01T10:26:01.842538+00:00'
[2024-08-01T10:35:51.594+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-01T10:35:51.605+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-01T10:35:51.605+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kezekte_etl.py", line 53, in transform_data
    for data in datasets:
TypeError: 'NoneType' object is not iterable
[2024-08-01T10:35:51.610+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=kezekte_etl, task_id=transform_data, run_id=manual__2024-08-01T10:26:01.842538+00:00, execution_date=20240801T102601, start_date=20240801T103551, end_date=20240801T103551
[2024-08-01T10:35:51.616+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 95 for task transform_data ('NoneType' object is not iterable; 339)
[2024-08-01T10:35:51.630+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-01T10:35:51.639+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-01T10:35:51.640+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
