[2024-08-02T14:16:11.011+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-02T14:16:11.026+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kezekte_etl.raw_data_to_psdb manual__2024-08-02T14:16:05.962745+00:00 [queued]>
[2024-08-02T14:16:11.029+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kezekte_etl.raw_data_to_psdb manual__2024-08-02T14:16:05.962745+00:00 [queued]>
[2024-08-02T14:16:11.029+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-02T14:16:11.035+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): raw_data_to_psdb> on 2024-08-02 14:16:05.962745+00:00
[2024-08-02T14:16:11.040+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2250) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-02T14:16:11.040+0000] {standard_task_runner.py:63} INFO - Started process 2252 to run task
[2024-08-02T14:16:11.041+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kezekte_etl', 'raw_data_to_psdb', 'manual__2024-08-02T14:16:05.962745+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/kezekte_etl.py', '--cfg-path', '/tmp/tmpp5bb710l']
[2024-08-02T14:16:11.042+0000] {standard_task_runner.py:91} INFO - Job 173: Subtask raw_data_to_psdb
[2024-08-02T14:16:11.060+0000] {task_command.py:426} INFO - Running <TaskInstance: kezekte_etl.raw_data_to_psdb manual__2024-08-02T14:16:05.962745+00:00 [running]> on host cd4398d9193e
[2024-08-02T14:16:11.093+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kezekte_etl' AIRFLOW_CTX_TASK_ID='raw_data_to_psdb' AIRFLOW_CTX_EXECUTION_DATE='2024-08-02T14:16:05.962745+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-02T14:16:05.962745+00:00'
[2024-08-02T14:16:11.094+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-02T14:16:11.103+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-02T14:16:11.104+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: raw_data_to_psdb() missing 1 required positional argument: 'transform_data'
[2024-08-02T14:16:11.112+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=kezekte_etl, task_id=raw_data_to_psdb, run_id=manual__2024-08-02T14:16:05.962745+00:00, execution_date=20240802T141605, start_date=20240802T141611, end_date=20240802T141611
[2024-08-02T14:16:11.122+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 173 for task raw_data_to_psdb (raw_data_to_psdb() missing 1 required positional argument: 'transform_data'; 2252)
[2024-08-02T14:16:11.140+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-02T14:16:11.155+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-02T14:16:11.159+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
