[2024-07-30T15:08:19.099+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: kezekte_etl.transform_data manual__2024-07-30T15:08:16.598148+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
